config/routes.rb
Rails.application.routes.draw do
  resources :the_teams

  resources :abouts

  resources :portfolios

  resources :users

  #get 'users/new'

  root 'home#index'
  match '/signup',  to: 'users#new',   via: 'get'

=begin
these guys are way ahead of their time  
  match '/help',    to: 'home#help',   via: 'get'
  match '/about',   to: 'home/about',  via: 'get'
  match 'contact',  to: 'home/contact', via: 'get'
=end
  
end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
end

app/models/the_team.rb
class TheTeam < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }

	#i undestand very little of regexes.. note to self, read more on it
	VALID_EMAIL_REGEX = /\A[\W+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX }, 
						uniqueness: {case_sensitive: false }

	has_secure_password
	validates :password, length: { minimum: 6}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params[:about]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params[:portfolio]
    end
end

app/controllers/the_teams_controller.rb
class TheTeamsController < ApplicationController
  before_action :set_the_team, only: [:show, :edit, :update, :destroy]

  # GET /the_teams
  # GET /the_teams.json
  def index
    @the_teams = TheTeam.all
  end

  # GET /the_teams/1
  # GET /the_teams/1.json
  def show
  end

  # GET /the_teams/new
  def new
    @the_team = TheTeam.new
  end

  # GET /the_teams/1/edit
  def edit
  end

  # POST /the_teams
  # POST /the_teams.json
  def create
    @the_team = TheTeam.new(the_team_params)

    respond_to do |format|
      if @the_team.save
        format.html { redirect_to @the_team, notice: 'The team was successfully created.' }
        format.json { render :show, status: :created, location: @the_team }
      else
        format.html { render :new }
        format.json { render json: @the_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /the_teams/1
  # PATCH/PUT /the_teams/1.json
  def update
    respond_to do |format|
      if @the_team.update(the_team_params)
        format.html { redirect_to @the_team, notice: 'The team was successfully updated.' }
        format.json { render :show, status: :ok, location: @the_team }
      else
        format.html { render :edit }
        format.json { render json: @the_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /the_teams/1
  # DELETE /the_teams/1.json
  def destroy
    @the_team.destroy
    respond_to do |format|
      format.html { redirect_to the_teams_url, notice: 'The team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_the_team
      @the_team = TheTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def the_team_params
      params[:the_team]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/the_teams_helper.rb
module TheTeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/_form.html.erb
<%= form_for(@about) do |f| %>
  <% if @about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% @about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing about</h1>

<%= render 'form' %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<h1>About Technology Kenya</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <!-- unless i find a very good reason i dont see why is should keep you
  <tbody>
    <% @abouts.each do |about| %>
      <tr>
        <td><%= link_to 'Show', about %></td>
        <td><%= link_to 'Edit', edit_about_path(about) %></td>
        <td><%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>-->
</table>

<br>

<!--<%= link_to 'New About', new_about_path %>-->

app/views/abouts/new.html.erb
<h1>New about</h1>

<%= render 'form' %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>

app/views/home/index.html.erb
<div class="center hero_unit">
	<h1>Welcome To Tech Drew</h1>
	<h2> This is the home page</h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Techmtaa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- navigation links-->
	<%= link_to "Home", root_path %>
	<%= link_to "About", abouts_path %>
	<%= link_to "Portfolio", portfolios_path %>
	<%= link_to "The Team", the_teams_path %>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails,env.development? %>
	</div>



</body>
</html>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<h1>Our Portfolio</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <!-- These idiots can be updated using an admin account, i mean admin account... keep them around until you create one. users cant even know about it.
  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>-->
</table>

<br>

<!--as i said above, admin account <%= link_to 'New Portfolio', new_portfolio_path %>-->

app/views/portfolios/new.html.erb
<h1>New portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>

app/views/the_teams/_form.html.erb
<%= form_for(@the_team) do |f| %>
  <% if @the_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@the_team.errors.count, "error") %> prohibited this the_team from being saved:</h2>

      <ul>
      <% @the_team.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/the_teams/edit.html.erb
<h1>Editing the_team</h1>

<%= render 'form' %>

<%= link_to 'Show', @the_team %> |
<%= link_to 'Back', the_teams_path %>

app/views/the_teams/index.html.erb
<h1>Technology Kenya Team</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <!-- Get ths idiots out of my face and give me very sweet html and css for a nice team
  <tbody>
    <% @the_teams.each do |the_team| %>
      <tr>
        <td><%= link_to 'Show', the_team %></td>
        <td><%= link_to 'Edit', edit_the_team_path(the_team) %></td>
        <td><%= link_to 'Destroy', the_team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>-->
</table>

<br>

<!--<%= link_to 'New The team', new_the_team_path %>-->

app/views/the_teams/new.html.erb
<h1>New the_team</h1>

<%= render 'form' %>

<%= link_to 'Back', the_teams_path %>

app/views/the_teams/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_the_team_path(@the_team) %> |
<%= link_to 'Back', the_teams_path %>

app/views/users/new.html.erb
<div><h1>Sign Up<h1></div>
<div>
	<p>Please fill in the following form to sign up</p>
	
</div>